In [1]:
import pandas as pd

In [ ]:
df=pd.read_csv("Salaries.csv")

In [ ]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [ ]:
#CHECK A PARTICULR COLUMN TYPE
df['salary'].dtype

dtype('int64')

In [ ]:
df['salary'].dtype

dtype('int64')

In [ ]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [ ]:
df.shape

(78, 6)

In [ ]:
df.values

array([['Prof', 'B', 56, 49, 'Male', 186960],
       ['Prof', 'A', 12, 6, 'Male', 93000],
       ['Prof', 'A', 23, 20, 'Male', 110515],
       ['Prof', 'A', 40, 31, 'Male', 131205],
       ['Prof', 'B', 20, 18, 'Male', 104800],
       ['Prof', 'A', 20, 20, 'Male', 122400],
       ['AssocProf', 'A', 20, 17, 'Male', 81285],
       ['Prof', 'A', 18, 18, 'Male', 126300],
       ['Prof', 'A', 29, 19, 'Male', 94350],
       ['Prof', 'A', 51, 51, 'Male', 57800],
       ['Prof', 'B', 39, 33, 'Male', 128250],
       ['Prof', 'B', 23, 23, 'Male', 134778],
       ['AsstProf', 'B', 1, 0, 'Male', 88000],
       ['Prof', 'B', 35, 33, 'Male', 162200],
       ['Prof', 'B', 25, 19, 'Male', 153750],
       ['Prof', 'B', 17, 3, 'Male', 150480],
       ['AsstProf', 'B', 8, 3, 'Male', 75044],
       ['AsstProf', 'B', 4, 0, 'Male', 92000],
       ['Prof', 'A', 19, 7, 'Male', 107300],
       ['Prof', 'A', 29, 27, 'Male', 150500],
       ['AsstProf', 'B', 4, 4, 'Male', 92000],
       ['Prof', 'A', 33, 30, 'Male', 103106],
       ['AsstProf', 'A', 4, 2, 'Male', 73000],
       ['AsstProf', 'A', 2, 0, 'Male', 85000],
       ['Prof', 'A', 30, 23, 'Male', 91100],
       ['Prof', 'B', 35, 31, 'Male', 99418],
       ['Prof', 'A', 38, 19, 'Male', 148750],
       ['Prof', 'A', 45, 43, 'Male', 155865],
       ['AsstProf', 'B', 7, 2, 'Male', 91300],
       ['Prof', 'B', 21, 20, 'Male', 123683],
       ['AssocProf', 'B', 9, 7, 'Male', 107008],
       ['Prof', 'B', 22, 21, 'Male', 155750],
       ['Prof', 'A', 27, 19, 'Male', 103275],
       ['Prof', 'B', 18, 18, 'Male', 120000],
       ['AssocProf', 'B', 12, 8, 'Male', 119800],
       ['Prof', 'B', 28, 23, 'Male', 126933],
       ['Prof', 'B', 45, 45, 'Male', 146856],
       ['Prof', 'A', 20, 8, 'Male', 102000],
       ['AsstProf', 'B', 4, 3, 'Male', 91000],
       ['Prof', 'B', 18, 18, 'Female', 129000],
       ['Prof', 'A', 39, 36, 'Female', 137000],
       ['AssocProf', 'A', 13, 8, 'Female', 74830],
       ['AsstProf', 'B', 4, 2, 'Female', 80225],
       ['AsstProf', 'B', 5, 0, 'Female', 77000],
       ['Prof', 'B', 23, 19, 'Female', 151768],
       ['Prof', 'B', 25, 25, 'Female', 140096],
       ['AsstProf', 'B', 11, 3, 'Female', 74692],
       ['AssocProf', 'B', 11, 11, 'Female', 103613],
       ['Prof', 'B', 17, 17, 'Female', 111512],
       ['Prof', 'B', 17, 18, 'Female', 122960],
       ['AsstProf', 'B', 10, 5, 'Female', 97032],
       ['Prof', 'B', 20, 14, 'Female', 127512],
       ['Prof', 'A', 12, 0, 'Female', 105000],
       ['AsstProf', 'A', 5, 3, 'Female', 73500],
       ['AssocProf', 'A', 25, 22, 'Female', 62884],
       ['AsstProf', 'A', 2, 0, 'Female', 72500],
       ['AssocProf', 'A', 10, 8, 'Female', 77500],
       ['AsstProf', 'A', 3, 1, 'Female', 72500],
       ['Prof', 'B', 36, 26, 'Female', 144651],
       ['AssocProf', 'B', 12, 10, 'Female', 103994],
       ['AsstProf', 'B', 3, 3, 'Female', 92000],
       ['AssocProf', 'B', 13, 10, 'Female', 103750],
       ['AssocProf', 'B', 14, 7, 'Female', 109650],
       ['Prof', 'A', 29, 27, 'Female', 91000],
       ['AssocProf', 'A', 26, 24, 'Female', 73300],
       ['Prof', 'A', 36, 19, 'Female', 117555],
       ['AsstProf', 'A', 7, 6, 'Female', 63100],
       ['Prof', 'A', 17, 11, 'Female', 90450],
       ['AsstProf', 'A', 4, 2, 'Female', 77500],
       ['Prof', 'A', 28, 7, 'Female', 116450],
       ['AsstProf', 'A', 8, 3, 'Female', 78500],
       ['AssocProf', 'B', 12, 9, 'Female', 71065],
       ['Prof', 'B', 24, 15, 'Female', 161101],
       ['Prof', 'B', 18, 10, 'Female', 105450],
       ['AssocProf', 'B', 19, 6, 'Female', 104542],
       ['Prof', 'B', 17, 17, 'Female', 124312],
       ['Prof', 'A', 28, 14, 'Female', 109954],
       ['Prof', 'A', 23, 15, 'Female', 109646]], dtype=object)

In [ ]:
print(df.mean())

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

<ipython-input-15-f98cceecb4a0>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df.mean())

In [ ]:
df['salary'].mean()

108023.78205128205

In [ ]:
#Calcute mean salary for each professor
df.groupby('rank')[['salary']].mean()

                  salary
rank
AssocProf   91786.230769
AsstProf    81362.789474
Prof       123624.804348

In [ ]:
df.groupby('sex')[['salary']].mean()

               salary
sex
Female  101002.410256
Male    115045.153846

In [ ]:
#Calculate mean salary for each professor rank
df_sub = df[df['salary']>120000]
print(df_sub)

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [ ]:
#Select rows by their position
df[10:20]

        rank discipline  phd  service   sex  salary
10      Prof          B   39       33  Male  128250
11      Prof          B   23       23  Male  134778
12  AsstProf          B    1        0  Male   88000
13      Prof          B   35       33  Male  162200
14      Prof          B   25       19  Male  153750
15      Prof          B   17        3  Male  150480
16  AsstProf          B    8        3  Male   75044
17  AsstProf          B    4        0  Male   92000
18      Prof          A   19        7  Male  107300
19      Prof          A   29       27  Male  150500

In [ ]:
df['rank'],['salary']

(0          Prof
 1          Prof
 2          Prof
 3          Prof
 4          Prof
         ...
 73         Prof
 74    AssocProf
 75         Prof
 76         Prof
 77         Prof
 Name: rank, Length: 78, dtype: object,
 ['salary'])

In [ ]:
#Select rows by their label
df_sub.iloc[10:20,[0,3,4,5]]

    rank  service     sex  salary
26  Prof       19    Male  148750
27  Prof       43    Male  155865
29  Prof       20    Male  123683
31  Prof       21    Male  155750
35  Prof       23    Male  126933
36  Prof       45    Male  146856
39  Prof       18  Female  129000
40  Prof       36  Female  137000
44  Prof       19  Female  151768
45  Prof       25  Female  140096

In [ ]:
df_sub.loc[10:20,['rank','sex','salary']]

    rank   sex  salary
10  Prof  Male  128250
11  Prof  Male  134778
13  Prof  Male  162200
14  Prof  Male  153750
15  Prof  Male  150480
19  Prof  Male  150500

In [ ]:
df_sub.shape

(25, 6)

In [ ]:
#Select rows by their labels
df_sub.iloc[10:20,[0,3,4,5]]

    rank  service     sex  salary
26  Prof       19    Male  148750
27  Prof       43    Male  155865
29  Prof       20    Male  123683
31  Prof       21    Male  155750
35  Prof       23    Male  126933
36  Prof       45    Male  146856
39  Prof       18  Female  129000
40  Prof       36  Female  137000
44  Prof       19  Female  151768
45  Prof       25  Female  140096

In [ ]:
df.iloc[0] #1st row of data frame

rank            Prof
discipline         B
phd               56
service           49
sex             Male
salary        186960
Name: 0, dtype: object

In [ ]:
df.iloc[1] #

rank           Prof
discipline        A
phd              12
service           6
sex            Male
salary        93000
Name: 1, dtype: object

In [ ]:
df.iloc[-1]

rank            Prof
discipline         A
phd               23
service           15
sex           Female
salary        109646
Name: 77, dtype: object

In [ ]:
df.iloc[:,0] #first column

0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
        ...
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, Length: 78, dtype: object

In [ ]:
df.iloc[:,-1] #last column

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
#creat a new data from the original sorted by the column salary
df_sorted = df.sort_values(by=['service','salary'],ascending=[True,False])
df_sorted.head(10)

        rank discipline  phd  service     sex  salary
52      Prof          A   12        0  Female  105000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
28  AsstProf          B    7        2    Male   91300
42  AsstProf          B    4        2  Female   80225
68  AsstProf          A    4        2  Female   77500

HOTEL BOOKING

In [2]:
df_hotel=pd.read_csv("hotel_bookings.csv")

In [3]:
df_hotel.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [ ]:
df_hotel.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
df_hotel.dtypes
print(df_hotel.mean())

is_canceled                          0.544238
lead_time                           99.665620
arrival_date_year                 2015.489623
arrival_date_week_number            28.785334
arrival_date_day_of_month           15.963813
stays_in_weekend_nights              1.265328
stays_in_week_nights                 3.377031
adults                               1.952205
children                             0.121535
babies                               0.015294
is_repeated_guest                    0.000000
previous_cancellations               0.000000
previous_bookings_not_canceled       0.000000
booking_changes                      0.217261
agent                              215.289282
company                            232.637037
days_in_waiting_list                 1.404479
adr                                 90.993664
required_car_parking_spaces          0.070736
total_of_special_requests            0.546770
dtype: float64

<ipython-input-27-ca98f2863c3a>:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df_hotel.mean())

In [ ]:
df_hotel.shape

(81537, 32)

In [ ]:
df_hotel['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [ ]:
print(df_hotel.mean())

is_canceled                          0.530520
lead_time                          112.695206
arrival_date_year                 2016.041122
arrival_date_week_number            28.165471
arrival_date_day_of_month           15.699327
stays_in_weekend_nights              0.983210
stays_in_week_nights                 2.669708
adults                               1.857034
children                             0.101799
babies                               0.008548
is_repeated_guest                    0.034083
previous_cancellations               0.113004
previous_bookings_not_canceled       0.153562
booking_changes                      0.203956
agent                              113.561888
company                            196.211543
days_in_waiting_list                 2.875713
adr                                 98.060807
required_car_parking_spaces          0.071820
total_of_special_requests            0.469860
dtype: float64

<ipython-input-53-012158041fda>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(df_hotel.mean())

In [ ]:
df_hotel['arrival_date_year'].mean()

2016.0411224352135

In [ ]:
df_hotel.groupby('arrival_date_month')[['arrival_date_year']].mean()

                    arrival_date_year
arrival_date_month
April                     2016.509379
August                    2015.901118
December                  2015.496278
February                  2016.525497
January                   2016.587754
July                      2016.036936
June                      2016.528148
March                     2016.483432
May                       2016.527222
November                  2015.536174
October                   2015.441312
September                 2015.383855

In [ ]:
df_sub = df_hotel[df_hotel['lead_time']>100]
print(df_sub)

             hotel  is_canceled  lead_time  arrival_date_year  \
0     Resort Hotel            0        342               2015
1     Resort Hotel            0        737               2015
24    Resort Hotel            0        127               2015
30    Resort Hotel            0        118               2015
44    Resort Hotel            0        107               2015
...            ...          ...        ...                ...
7318  Resort Hotel            1        434               2016
7319  Resort Hotel            1        190               2016
7320  Resort Hotel            1        215               2016
7322  Resort Hotel            1        209               2016
7323  Resort Hotel            1        208               2016

     arrival_date_month  arrival_date_week_number  arrival_date_day_of_month  \
0                  July                      27.0                        1.0
1                  July                      27.0                        1.0
24                 July                      27.0                        1.0
30                 July                      27.0                        1.0
44                 July                      27.0                        2.0
...                 ...                       ...                        ...
7318             August                      32.0                        2.0
7319             August                      32.0                        2.0
7320             August                      32.0                        2.0
7322             August                      32.0                        2.0
7323                Aug                       NaN                        NaN

      stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                         0.0                   0.0     2.0  ...
1                         0.0                   0.0     2.0  ...
24                        2.0                   5.0     2.0  ...
30                        4.0                  10.0     1.0  ...
44                        2.0                   5.0     2.0  ...
...                       ...                   ...     ...  ...
7318                      2.0                   5.0     2.0  ...
7319                      2.0                   5.0     3.0  ...
7320                      2.0                   5.0     2.0  ...
7322                      4.0                  10.0     2.0  ...
7323                      NaN                   NaN     NaN  ...

      deposit_type  agent company days_in_waiting_list customer_type     adr  \
0       No Deposit    NaN     NaN                  0.0     Transient    0.00
1       No Deposit    NaN     NaN                  0.0     Transient    0.00
24      No Deposit  115.0     NaN                  0.0      Contract   94.95
30      No Deposit    NaN     NaN                  0.0     Transient   62.00
44      No Deposit  240.0     NaN                  0.0     Transient  110.70
...            ...    ...     ...                  ...           ...     ...
7318    No Deposit   40.0     NaN                  0.0      Contract  160.50
7319    No Deposit  240.0     NaN                  0.0     Transient  250.00
7320    No Deposit  240.0     NaN                  0.0     Transient  240.00
7322    No Deposit  240.0     NaN                  0.0     Transient  158.00
7323           NaN    NaN     NaN                  NaN           NaN     NaN

      required_car_parking_spaces  total_of_special_requests  \
0                             0.0                        0.0
1                             0.0                        0.0
24                            0.0                        1.0
30                            0.0                        2.0
44                            0.0                        2.0
...                           ...                        ...
7318                          0.0                        0.0
7319                          0.0                        0.0
7320                          0.0                        0.0
7322                          0.0                        0.0
7323                          NaN                        NaN

      reservation_status reservation_status_date
0              Check-Out              2015-07-01
1              Check-Out              2015-07-01
24             Check-Out              2015-07-01
30             Check-Out              2015-07-15
44             Check-Out              2015-07-09
...                  ...                     ...
7318            Canceled              2015-10-14
7319            Canceled              2016-03-10
7320            Canceled              2016-07-26
7322            Canceled              2016-01-08
7323                 NaN                     NaN

[3108 rows x 32 columns]

In [ ]:
df[10:20]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
10,Resort Hotel,1,23,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,123.00,0.0,0.0,Canceled,2015-06-23
11,Resort Hotel,0,35,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,145.00,0.0,0.0,Check-Out,2015-07-05
12,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0.0,3.0,Check-Out,2015-07-05
13,Resort Hotel,0,18,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,154.77,0.0,1.0,Check-Out,2015-07-05
14,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,241.0,NaN,0,Transient,94.71,0.0,0.0,Check-Out,2015-07-05
15,Resort Hotel,0,68,2015,July,27,1,0,4,2,...,No Deposit,240.0,NaN,0,Transient,97.00,0.0,3.0,Check-Out,2015-07-05
16,Resort Hotel,0,37,2015,July,27,1,0,4,2,...,No Deposit,8.0,NaN,0,Contract,97.50,0.0,0.0,Check-Out,2015-07-05
17,Resort Hotel,0,12,2015,July,27,1,0,1,2,...,No Deposit,240.0,NaN,0,Transient,88.20,0.0,0.0,Check-Out,2015-07-02
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0.0,0.0,Check-Out,2015-07-02
19,Resort Hotel,0,7,2015,July,27,1,0,4,2,...,No Deposit,250.0,NaN,0,Transient,153.00,0.0,1.0,Check-Out,2015-07-05

In [ ]:
df_hotel['hotel'],['lead_time']

(0        Resort Hotel
 1        Resort Hotel
 2        Resort Hotel
 3        Resort Hotel
 4        Resort Hotel
              ...
 81532      City Hotel
 81533      City Hotel
 81534      City Hotel
 81535      City Hotel
 81536      City Hotel
 Name: hotel, Length: 81537, dtype: object,
 ['lead_time'])

In [ ]:
df_sub.iloc[10:30,[1,2,4,8,12,15,18]]

,is_canceled,lead_time,arrival_date_month,stays_in_week_nights,meal,distribution_channel,previous_bookings_not_canceled
85,0,324,July,10.0,HB,TA/TO,0.0
93,0,109,July,1.0,BB,TA/TO,0.0
94,1,109,July,2.0,BB,TA/TO,0.0
98,0,101,July,5.0,BB,TA/TO,0.0
99,0,102,July,5.0,BB,Direct,0.0
104,0,102,July,5.0,BB,TA/TO,0.0
107,1,102,July,5.0,BB,TA/TO,0.0
108,0,115,July,5.0,BB,TA/TO,0.0
109,0,102,July,5.0,BB,TA/TO,0.0
114,1,101,July,6.0,BB,TA/TO,0.0
115,0,109,July,6.0,BB,TA/TO,0.0
143,0,109,July,3.0,BB,TA/TO,0.0
152,1,101,July,5.0,HB,TA/TO,0.0
157,0,110,July,7.0,BB,TA/TO,0.0
160,0,115,July,4.0,BB,TA/TO,0.0
161,0,111,July,3.0,BB,TA/TO,0.0
167,0,111,July,0.0,BB,TA/TO,0.0
175,0,104,July,3.0,BB,TA/TO,0.0
179,0,104,July,5.0,BB,TA/TO,0.0
182,0,258,July,5.0,BB,TA/TO,0.0

In [ ]:
df_sub.loc[20:70,['hotel','lead_time','arrival_date_month']]

           hotel  lead_time arrival_date_month
24  Resort Hotel        127               July
30  Resort Hotel        118               July
44  Resort Hotel        107               July
47  Resort Hotel        113               July
50  Resort Hotel        113               July

In [ ]:
df_hotel.iloc[0]

hotel                             Resort Hotel
is_canceled                                  0
lead_time                                  342
arrival_date_year                         2015
arrival_date_month                        July
arrival_date_week_number                  27.0
arrival_date_day_of_month                  1.0
stays_in_weekend_nights                    0.0
stays_in_week_nights                       0.0
adults                                     2.0
children                                   0.0
babies                                     0.0
meal                                        BB
country                                    PRT
market_segment                          Direct
distribution_channel                    Direct
is_repeated_guest                          0.0
previous_cancellations                     0.0
previous_bookings_not_canceled             0.0
reserved_room_type                           C
assigned_room_type                           C
booking_changes                            3.0
deposit_type                        No Deposit
agent                                      NaN
company                                    NaN
days_in_waiting_list                       0.0
customer_type                        Transient
adr                                        0.0
required_car_parking_spaces                0.0
total_of_special_requests                  0.0
reservation_status                   Check-Out
reservation_status_date             2015-07-01
Name: 0, dtype: object

In [ ]:
df_hotel.iloc[-1]

hotel                             Resort Hotel
is_canceled                                  1
lead_time                                  208
arrival_date_year                         2016
arrival_date_month                         Aug
arrival_date_week_number                   NaN
arrival_date_day_of_month                  NaN
stays_in_weekend_nights                    NaN
stays_in_week_nights                       NaN
adults                                     NaN
children                                   NaN
babies                                     NaN
meal                                       NaN
country                                    NaN
market_segment                             NaN
distribution_channel                       NaN
is_repeated_guest                          NaN
previous_cancellations                     NaN
previous_bookings_not_canceled             NaN
reserved_room_type                         NaN
assigned_room_type                         NaN
booking_changes                            NaN
deposit_type                               NaN
agent                                      NaN
company                                    NaN
days_in_waiting_list                       NaN
customer_type                              NaN
adr                                        NaN
required_car_parking_spaces                NaN
total_of_special_requests                  NaN
reservation_status                         NaN
reservation_status_date                    NaN
Name: 7323, dtype: object

In [ ]:
df_hotel.iloc[:,0]

0       Resort Hotel
1       Resort Hotel
2       Resort Hotel
3       Resort Hotel
4       Resort Hotel
            ...
7319    Resort Hotel
7320    Resort Hotel
7321    Resort Hotel
7322    Resort Hotel
7323    Resort Hotel
Name: hotel, Length: 7324, dtype: object

In [ ]:
df_hotel.iloc[:,-1]

0       2015-07-01
1       2015-07-01
2       2015-07-02
3       2015-07-02
4       2015-07-03
           ...
7319    2016-03-10
7320    2016-07-26
7321    2016-06-19
7322    2016-01-08
7323           NaN
Name: reservation_status_date, Length: 7324, dtype: object

In [ ]:
df_hotel_sorted = df_hotel.sort_values(by=['hotel','lead_time'],ascending=[True,False])
df_hotel_sorted.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
1,Resort Hotel,0,737,2015,July,27.0,1.0,0.0,0.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
4182,Resort Hotel,0,709,2016,February,9.0,25.0,8.0,20.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,68.0,0.0,0.0,Check-Out,2016-03-24
5704,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04
5705,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04
5707,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04
5708,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04
5712,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04
5713,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,26.0,0.0,0.0,Canceled,2016-05-03
5714,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04
5715,Resort Hotel,1,468,2016,May,20.0,12.0,0.0,2.0,2.0,...,No Deposit,249.0,NaN,0.0,Transient-Party,67.0,0.0,0.0,Canceled,2016-03-04

In [4]:
df_hotel.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64